# Generated by Django 4.2.5 on 2023-09-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='CnnVectors',
            fields=[
            ],
        ),
    ]
