# Generated by Django 4.2.5 on 2023-10-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sets', '0003_userdataembedding_delete_dataembedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatacollection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userdataembedding',
            options={},
        ),
        migrations.AlterModelTable(
            name='userdatacollection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userdataembedding',
            table=None,
        ),
    ]
