# Generated by Django 4.2.5 on 2023-10-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sets', '0004_alter_userdatacollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataembedding',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='data_sets.userdatacollection'),
        ),
    ]
